# Schema for the configuration files of the SGSE Site Support module.
stop14_taxonomy_browser.settings:
  type: config_object
  label: 'Stop14 Taxonomy Browser Settings'
  mapping:
    example:
      type: string
      label: 'Example'
